const AUTH_KEY = "yourr_party_rentals_gallery_admin_auth";
const loginSection = document.getElementById("admin-login");
const panelSection = document.getElementById("admin-panel");
const loginForm = document.getElementById("admin-login-form");
const loginStatus = document.getElementById("login-status");
const logoutBtn = document.getElementById("logout-btn");
const uploadForm = document.getElementById("upload-form");
const uploadStatus = document.getElementById("upload-status");
const adminGalleryGrid = document.getElementById("admin-gallery-grid");
const settingsForm = document.getElementById("settings-form");
const settingsStatus = document.getElementById("settings-status");
const previewModal = document.getElementById("preview-modal");
const previewImage = document.getElementById("preview-image");
const previewTitle = document.getElementById("preview-title");
const previewCaption = document.getElementById("preview-caption");
const closePreviewBtn = document.getElementById("close-preview-btn");
const availabilityForm = document.getElementById("availability-form");
const availabilityStatus = document.getElementById("availability-status");
const catalogForm = document.getElementById("catalog-form");
const inventoryEditor = document.getElementById("inventory-editor");
const packageEditor = document.getElementById("package-editor");
const addPackageBtn = document.getElementById("add-package-btn");
const catalogStatus = document.getElementById("catalog-status");
let availabilityOverrides = {};
const keys = ["tables", "chairs", "canopies", "fans", "iceChests"];
function getCredentials() { try { const value = JSON.parse(sessionStorage.getItem(AUTH_KEY) || "null"); return value && value.username && value.password ? value : null; } catch (error) { return null; } }
function authHeader() { const credentials = getCredentials(); return credentials ? { Authorization: `Basic ${btoa(`${credentials.username}:${credentials.password}`)}` } : {}; }
function fileToDataUrl(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); }
async function verifyCredentials(username, password) { const response = await fetch("/api/admin/ping", { headers: { Authorization: `Basic ${btoa(`${username}:${password}`)}` } }); return response.ok; }
function showPanel() { loginSection.hidden = true; panelSection.hidden = false; loadAdminGallery(); loadSettings(); loadAvailability(); loadCatalog(); }
function showLogin() { loginSection.hidden = false; panelSection.hidden = true; }
async function loadAdminGallery() { const response = await fetch("/api/gallery"); renderAdminGallery(response.ok ? await response.json() : []); }
function renderAdminGallery(images) { adminGalleryGrid.innerHTML = images.length ? "" : "<p>No uploaded images yet. Add one above.</p>"; images.forEach((image) => { const figure = document.createElement("figure"); const img = document.createElement("img"); img.src = image.url; img.alt = image.caption || "Uploaded gallery image"; img.onclick = () => openPreview(image); figure.appendChild(img); const caption = document.createElement("figcaption"); caption.textContent = image.caption || "(no caption)"; figure.appendChild(caption); const deleteButton = document.createElement("button"); deleteButton.type = "button"; deleteButton.textContent = "Delete"; deleteButton.onclick = () => deleteImage(image.id); figure.appendChild(deleteButton); const previewButton = document.createElement("button"); previewButton.type = "button"; previewButton.className = "preview-btn"; previewButton.textContent = "Preview"; previewButton.onclick = () => openPreview(image); figure.appendChild(previewButton); adminGalleryGrid.appendChild(figure); }); }
function openPreview(image) { previewImage.src = image.url; previewImage.alt = image.caption || "Uploaded gallery image"; previewTitle.textContent = image.caption || "Image Preview"; previewCaption.textContent = image.caption || ""; previewModal.hidden = false; }
function closePreview() { previewModal.hidden = true; previewImage.src = ""; }
async function loadSettings() { const response = await fetch("/api/admin/settings", { headers: authHeader() }); if (response.ok) Object.entries(await response.json()).forEach(([key, value]) => { if (settingsForm.elements[key]) settingsForm.elements[key].value = value; }); }
async function loadAvailability() { const response = await fetch("/api/admin/availability", { headers: authHeader() }); if (response.ok) availabilityOverrides = await response.json(); }
async function loadCatalog() { const response = await fetch("/api/admin/catalog", { headers: authHeader() }); if (response.ok) renderCatalogEditor(await response.json()); }
function renderCatalogEditor(catalog) { inventoryEditor.innerHTML = ""; catalog.items.forEach((item) => { const row = document.createElement("div"); row.className = "inventory-row"; row.dataset.key = item.key; row.innerHTML = `<strong>${item.name}</strong><label class="inventory-description-field">Description<input name="description" required></label><label>Inventory<input type="number" min="0" name="inventory" required></label><label>Price<input type="number" min="0" step=".01" name="price" required></label>`; row.querySelector('[name="description"]').value = item.description || ""; row.querySelector('[name="inventory"]').value = item.inventory; row.querySelector('[name="price"]').value = item.price; inventoryEditor.appendChild(row); }); packageEditor.innerHTML = ""; catalog.packages.forEach(addPackageEditor); }
function addPackageEditor(pkg = {}) { if (packageEditor.children.length >= 4) { catalogStatus.textContent = "A maximum of four packages can be displayed."; return; } const editor = document.createElement("fieldset"); editor.className = "package-editor-row"; editor.dataset.id = pkg.id || ""; editor.innerHTML = `<legend>Package ${packageEditor.children.length + 1}</legend><button type="button" class="remove-package-btn">Remove</button><label>Name<input name="packageName" required></label><label>Description<input name="packageDescription"></label><label>Package Price<input type="number" min="0" step=".01" name="packagePrice" required></label><div class="package-quantities"></div>`; editor.querySelector('[name="packageName"]').value = pkg.name || ""; editor.querySelector('[name="packageDescription"]').value = pkg.description || ""; editor.querySelector('[name="packagePrice"]').value = pkg.price || 0; keys.forEach((key) => { const label = document.createElement("label"); label.textContent = key; const input = document.createElement("input"); input.type = "number"; input.min = "0"; input.name = `package-${key}`; input.value = pkg.items?.[key] || 0; label.appendChild(input); editor.querySelector(".package-quantities").appendChild(label); }); editor.querySelector(".remove-package-btn").onclick = () => editor.remove(); packageEditor.appendChild(editor); }
loginForm.addEventListener("submit", async (event) => { event.preventDefault(); const data = new FormData(loginForm); const username = String(data.get("username") || "").trim(); const password = String(data.get("password") || ""); loginStatus.textContent = "Checking credentials..."; if (await verifyCredentials(username, password)) { sessionStorage.setItem(AUTH_KEY, JSON.stringify({ username, password })); loginForm.reset(); showPanel(); } else loginStatus.textContent = "Incorrect username or password."; });
logoutBtn.onclick = () => { sessionStorage.removeItem(AUTH_KEY); showLogin(); };
uploadForm.addEventListener("submit", async (event) => { event.preventDefault(); const data = new FormData(uploadForm); const file = data.get("image"); if (!file || !file.size) { uploadStatus.textContent = "Please choose an image file."; return; } uploadStatus.textContent = "Uploading..."; const response = await fetch("/api/gallery", { method: "POST", headers: { "Content-Type": "application/json", ...authHeader() }, body: JSON.stringify({ image: await fileToDataUrl(file), caption: String(data.get("caption") || "").trim() }) }); uploadStatus.textContent = response.ok ? "Image added to gallery." : "Upload failed."; if (response.ok) { uploadForm.reset(); loadAdminGallery(); } });
settingsForm.addEventListener("submit", async (event) => { event.preventDefault(); const response = await fetch("/api/admin/settings", { method: "PUT", headers: { "Content-Type": "application/json", ...authHeader() }, body: JSON.stringify(Object.fromEntries(new FormData(settingsForm).entries())) }); settingsStatus.textContent = response.ok ? "Business settings saved." : "Could not save business settings."; });
availabilityForm.elements.availabilityDate.onchange = (event) => { availabilityForm.elements.availabilitySlots.value = (availabilityOverrides[event.target.value] || []).join(", "); };
availabilityForm.addEventListener("submit", async (event) => { event.preventDefault(); const data = new FormData(availabilityForm); const date = String(data.get("availabilityDate") || ""); const slots = String(data.get("availabilitySlots") || "").split(",").map((slot) => slot.trim()).filter(Boolean); const response = await fetch("/api/admin/availability", { method: "PUT", headers: { "Content-Type": "application/json", ...authHeader() }, body: JSON.stringify({ date, slots }) }); availabilityStatus.textContent = response.ok ? "Date availability saved." : "Could not save availability."; });
addPackageBtn.onclick = () => addPackageEditor();
catalogForm.addEventListener("submit", async (event) => { event.preventDefault(); const items = [...inventoryEditor.children].map((row) => ({ key: row.dataset.key, description: row.querySelector('[name="description"]').value, inventory: Number(row.querySelector('[name="inventory"]').value || 0), price: Number(row.querySelector('[name="price"]').value || 0) })); const packages = [...packageEditor.children].map((editor) => ({ id: editor.dataset.id, name: editor.querySelector('[name="packageName"]').value, description: editor.querySelector('[name="packageDescription"]').value, price: Number(editor.querySelector('[name="packagePrice"]').value || 0), items: Object.fromEntries(keys.map((key) => [key, Number(editor.querySelector(`[name="package-${key}"]`).value || 0)])) })); const response = await fetch("/api/admin/catalog", { method: "PUT", headers: { "Content-Type": "application/json", ...authHeader() }, body: JSON.stringify({ items, packages }) }); if (response.ok) { renderCatalogEditor(await response.json()); catalogStatus.textContent = "Inventory and packages saved."; } else catalogStatus.textContent = "Could not save catalog."; });
closePreviewBtn.onclick = closePreview; previewModal.onclick = (event) => { if (event.target === previewModal) closePreview(); };
if (getCredentials()) showPanel(); else showLogin();
